spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
foo:
  rabbitmq:
    exchange: foo.exchange
    queue: foo.queue
    routingkey: foo.routingkey
server:  port: 1111